"""Abstract base class and shared types for HM-Arch memory layers.

Provides:

* :class:`LayerEntry` — the internal record type stored inside any layer.
* :class:`MemoryLayer` — abstract base that every layer (L0–L3) must
  subclass.
* :func:`_tokenize` / :func:`_token_overlap_score` — lightweight
  token-overlap scoring helpers used for in-memory retrieval.  The
  algorithm is intentionally identical to the one in
  :mod:`hm_arch.storage.vector` so that offline tests stay deterministic
  and no external API is required.
"""

from __future__ import annotations

import re
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional

from hm_arch.types import EventType, MemoryItem

# ---------------------------------------------------------------------------
# Token-overlap scoring (mirrors hm_arch.storage.vector, no import needed)
# ---------------------------------------------------------------------------

_TOKEN_RE = re.compile(r"[a-z0-9]+|[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")


def _tokenize(text: str) -> list[str]:
    """Return lowercase alphanumeric tokens plus individual CJK characters."""
    return _TOKEN_RE.findall(text.lower())


def _token_overlap_score(query_tokens: list[str], doc_tokens: list[str]) -> float:
    """Deterministic token-frequency overlap score in ``[0.0, 1.0]``.

    Returns ``0.0`` when either token list is empty.
    """
    if not query_tokens or not doc_tokens:
        return 0.0

    query_tf: dict[str, int] = {}
    for t in query_tokens:
        query_tf[t] = query_tf.get(t, 0) + 1

    doc_tf: dict[str, int] = {}
    for t in doc_tokens:
        doc_tf[t] = doc_tf.get(t, 0) + 1

    overlap = sum(min(cnt, doc_tf.get(tok, 0)) for tok, cnt in query_tf.items())
    denom = max(len(query_tokens), len(doc_tokens))
    return overlap / denom


# ---------------------------------------------------------------------------
# Internal record type
# ---------------------------------------------------------------------------


@dataclass
class LayerEntry:
    """A single record stored inside an in-memory layer.

    Parameters
    ----------
    entry_id:
        Unique identifier, generated by :meth:`new`.
    content:
        Raw text of the memory.
    event_type:
        Classification of the event that produced this memory.
    added_at:
        UTC timestamp recorded at insertion time.
    metadata:
        Arbitrary caller-supplied key/value pairs.
    retention:
        Current retention strength in ``[0, 1]``.  In-memory layers
        keep this at ``1.0`` — entries are either present or evicted.
    """

    entry_id: str
    content: str
    event_type: EventType
    added_at: datetime
    metadata: dict = field(default_factory=dict)
    retention: float = 1.0

    @staticmethod
    def new(
        content: str,
        event_type: EventType,
        metadata: Optional[dict] = None,
    ) -> "LayerEntry":
        """Create a fresh entry with a generated id and current UTC time."""
        return LayerEntry(
            entry_id=str(uuid.uuid4()),
            content=content,
            event_type=event_type,
            added_at=datetime.now(timezone.utc),
            metadata=dict(metadata) if metadata is not None else {},
        )


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------


class MemoryLayer(ABC):
    """Abstract base class for all memory layers (L0–L3).

    Concrete subclasses must implement :meth:`encode`, :meth:`retrieve`,
    and :meth:`clear`, and expose the read-only properties
    :attr:`layer_index`, :attr:`capacity`, and :attr:`size`.
    """

    # ------------------------------------------------------------------
    # Required properties
    # ------------------------------------------------------------------

    @property
    @abstractmethod
    def layer_index(self) -> int:
        """Integer layer index (0 = L0, 1 = L1, …)."""

    @property
    @abstractmethod
    def capacity(self) -> int:
        """Maximum number of entries this layer can hold at one time."""

    @property
    @abstractmethod
    def size(self) -> int:
        """Current number of entries stored in this layer."""

    # ------------------------------------------------------------------
    # Required methods
    # ------------------------------------------------------------------

    @abstractmethod
    def encode(
        self,
        content: str,
        event_type: EventType = EventType.OBSERVATION,
        metadata: Optional[dict] = None,
    ) -> str:
        """Add *content* to this layer and return the new entry id.

        When the layer is at capacity the **oldest** entry is evicted
        before the new one is inserted.
        """

    @abstractmethod
    def retrieve(self, query: str, top_k: int = 5) -> list[MemoryItem]:
        """Return up to *top_k* :class:`~hm_arch.types.MemoryItem` objects.

        Results are sorted by combined score
        (``retention × relevance × layer_priority``) descending.
        Ties are broken by entry id ascending for determinism.
        """

    @abstractmethod
    def clear(self) -> None:
        """Remove all entries from this layer."""
