"""JSONL stdio sidecar protocol for long-lived HM-Arch processes.

See ``docs/sidecar-protocol.md`` for the full contract. Golden fixtures live in
``fixtures/sidecar-protocol/``.
"""

from __future__ import annotations

from hm_arch.integrations.sidecar.protocol import (
    CURRENT_PROTOCOL_VERSION,
    FAIL_OPEN_OPERATIONS,
    SUPPORTED_OPERATIONS,
    ConsolidateParams,
    ConsolidateResult,
    ForgetParams,
    ForgetResult,
    HealthParams,
    HealthResult,
    InitializeParams,
    InitializeResult,
    ProtocolValidationError,
    RecordTurnParams,
    RecordTurnResult,
    RememberParams,
    RememberResult,
    SearchHit,
    SearchParams,
    SearchResult,
    ShutdownResult,
    SidecarError,
    SidecarOperation,
    SidecarRequest,
    SidecarResponse,
    SidecarTelemetry,
    fail_open_remember,
    fail_open_record_turn,
    fail_open_search,
    negotiate_capabilities,
    negotiate_protocol_version,
    parse_sidecar_request,
    parse_sidecar_response,
    serialize_sidecar_request,
    serialize_sidecar_response,
    structured_error,
    validate_operation,
    validate_protocol_version,
)

__all__ = [
    "CURRENT_PROTOCOL_VERSION",
    "FAIL_OPEN_OPERATIONS",
    "SUPPORTED_OPERATIONS",
    "ConsolidateParams",
    "ConsolidateResult",
    "ForgetParams",
    "ForgetResult",
    "HealthParams",
    "HealthResult",
    "InitializeParams",
    "InitializeResult",
    "ProtocolValidationError",
    "RecordTurnParams",
    "RecordTurnResult",
    "RememberParams",
    "RememberResult",
    "SearchHit",
    "SearchParams",
    "SearchResult",
    "ShutdownResult",
    "SidecarError",
    "SidecarOperation",
    "SidecarRequest",
    "SidecarResponse",
    "SidecarTelemetry",
    "fail_open_remember",
    "fail_open_record_turn",
    "fail_open_search",
    "negotiate_capabilities",
    "negotiate_protocol_version",
    "parse_sidecar_request",
    "parse_sidecar_response",
    "serialize_sidecar_request",
    "serialize_sidecar_response",
    "structured_error",
    "validate_operation",
    "validate_protocol_version",
]
